apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container-build

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: false
        default: https://index.docker.io/v1/
      appName:
        type: string
        required: true
      versionStart:
        type: string
        required: false
        default: "3.0"
      repo:
        type: string
        required: true

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        with:
          repository: ${{ inputs.repo }}
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Configure container registry credentials
        continue-on-error: true
        id: dockerconfig
        with:
          registry: ${{ inputs.registry }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: cloudbees-io/kaniko@v1
        name: Build container image
        kind: build
        with:
          destination: ${{ vars.DOCKER_USER }}/${{ inputs.appName }}:${{ inputs.versionStart }}-${{ cloudbees.version }}
          tar-path: container-image.tar
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
      - uses: cloudbees-io/asset-chain-utils/upload-binary@v1
        name: Upload binary from container build
        continue-on-error: true
        id: upload-binary
        with:
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
          debug: "true"
          # alias: ${{ vars.DOCKER_USER }}/${{ inputs.appName }}:${{ inputs.versionStart }}-${{ cloudbees.version }}
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Built and pushed image to docker hub

            [Docker Hub](https://hub.docker.com/repository/docker/${{ vars.DOCKER_USER }}/${{ inputs.appName }}/tags)

            Deployed ${{ vars.DOCKER_USER }}/${{ inputs.appName }}:${{ inputs.versionStart }}-${{ cloudbees.version }}
          format: MARKDOWN
